version: 4

shared:
    settings:
        email: 'yspark-devel@verizonmedia.com'
    annotations:
        screwdriver.cd/cpu: LOW
        screwdriver.cd/ram: LOW
        screwdriver.cd/timeout: 720
    template: HadoopTools/gridci-6_10_3@latest

cache:
    event: [$SD_ARTIFACTS_DIR]

jobs:
    component:
        requires: [~commit, ~sd@314435:component]
        steps:
            - environment: 'source sd:environment'
            - build: gmake build
            - junit: gmake test
            - regression: echo 'Skip regression'
            - package: gmake package
            - publish: gmake publish
            - statefile: echo 'Skip statefile'
            - git_tag: gmake git_tag
            - dist_tag: echo 'Skip dist_tag'

    pull_request:
        requires: [~pr]
        steps:
            - environment: 'source sd:environment'
            - build: gmake build
            - junit: gmake test
            - regression: echo 'Skip regression'
            - package: gmake package
            - publish: echo 'Skip publish' 
            - statefile: echo 'Skip statefile'
            - git_tag: echo 'Skip git_tag'
            - dist_tag: echo 'Skip dist_tag'
